import { createHash } from "node:crypto";
import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export const MANIFEST_FILENAME = "offline-manifest.json";
export const SERVICE_WORKER_FILENAME = "service-worker.js";
export const COURSE_RELEASE_OUTPUT_PATH = "course/current";

const PRIVATE_RELEASE_SEGMENTS = new Set(["__pycache__", "reference_source"]);

const GENERATED_FILENAMES = new Set([
  MANIFEST_FILENAME,
  SERVICE_WORKER_FILENAME,
]);

export function normalizeBasePath(value = "/") {
  const trimmed = value.trim();
  if (trimmed === "" || trimmed === "/") {
    return "/";
  }
  if (trimmed.includes(":") || trimmed.includes("?") || trimmed.includes("#")) {
    throw new Error("COURSE_BASE_PATH must be a URL path, not a full URL");
  }
  return `/${trimmed.replace(/^\/+|\/+$/g, "")}/`;
}

function sha256(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

async function listFiles(directory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries.sort((left, right) =>
    left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
  )) {
    const relativePath = path.posix.join(prefix, entry.name);
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listFiles(absolutePath, relativePath)));
    } else if (entry.isFile() && !GENERATED_FILENAMES.has(relativePath)) {
      files.push({ absolutePath, relativePath });
    }
  }

  return files;
}

export async function collectBuildAssets(outputDirectory, basePath) {
  const normalizedBasePath = normalizeBasePath(basePath);
  const files = await listFiles(outputDirectory);
  const assets = [];

  for (const file of files) {
    const contents = await readFile(file.absolutePath);
    assets.push({
      path: file.relativePath,
      url: `${normalizedBasePath}${file.relativePath}`,
      bytes: contents.byteLength,
      sha256: sha256(contents),
    });
  }

  return assets;
}

export function createOfflineManifest(assets, basePath) {
  const normalizedBasePath = normalizeBasePath(basePath);
  const payload = {
    schema_version: 1,
    base_path: normalizedBasePath,
    assets,
  };
  const version = sha256(JSON.stringify(payload)).slice(0, 20);
  const baseIdentifier = sha256(normalizedBasePath).slice(0, 10);

  return {
    ...payload,
    version,
    cache_name: `ucsb-xrp-course-shell-${baseIdentifier}-${version}`,
  };
}

export function renderServiceWorker(manifest) {
  const manifestUrl = `${manifest.base_path}${MANIFEST_FILENAME}`;
  const precacheUrls = [
    ...manifest.assets.map((asset) => asset.url),
    manifestUrl,
  ];
  const cachePrefix = manifest.cache_name.slice(
    0,
    manifest.cache_name.length - manifest.version.length,
  );

  return `/* Generated by scripts/offline-build.mjs. Do not edit. */
const CACHE_NAME = ${JSON.stringify(manifest.cache_name)};
const CACHE_PREFIX = ${JSON.stringify(cachePrefix)};
const SCOPE_PATH = ${JSON.stringify(manifest.base_path)};
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)};
const PRECACHE_PATHS = new Set(PRECACHE_URLS);

function navigationFallback(pathname) {
  if (!pathname.startsWith(SCOPE_PATH)) {
    return null;
  }

  const relativePath = pathname.slice(SCOPE_PATH.length).replace(/^\\/+|\\/+$/g, "");
  if (relativePath === "" || relativePath === "index.html") {
    return SCOPE_PATH + "index.html";
  }

  for (const application of ["ide", "dashboard", "guide"]) {
    if (relativePath === application || relativePath === application + "/index.html") {
      return SCOPE_PATH + application + "/index.html";
    }
  }

  return null;
}

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(CACHE_NAME);
      const requests = PRECACHE_URLS.map(
        (url) => new Request(url, { cache: "reload", credentials: "same-origin" }),
      );
      await cache.addAll(requests);
      await self.skipWaiting();
    } catch (error) {
      await caches.delete(CACHE_NAME);
      throw error;
    }
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    const previousNames = names.filter(
      (name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME,
    );
    // Keep the immediately preceding shell so a tab opened before an update
    // can still request one of its content-addressed worker or script files.
    await Promise.all(
      previousNames
        .slice(0, -1)
        .map((name) => caches.delete(name)),
    );
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    return;
  }

  if (request.mode === "navigate") {
    const fallbackUrl = navigationFallback(url.pathname);
    if (fallbackUrl !== null) {
      event.respondWith(
        fetch(request).catch(async () => {
          const cache = await caches.open(CACHE_NAME);
          const cached = await cache.match(
            new URL(fallbackUrl, self.location.origin).toString(),
          );
          if (cached === undefined) {
            throw new Error("Offline application entry is unavailable");
          }
          return cached;
        }),
      );
    }
    return;
  }

  const canonicalUrl = url.pathname;
  if (PRECACHE_PATHS.has(canonicalUrl)) {
    event.respondWith(
      caches
        .open(CACHE_NAME)
        .then((cache) => cache.match(url.toString(), { ignoreSearch: true }))
        .then((cached) => cached ?? fetch(request)),
    );
    return;
  }

  const isVersionedAsset = canonicalUrl.startsWith(SCOPE_PATH + "assets/");
  if (!isVersionedAsset) {
    return;
  }

  event.respondWith(
    caches
      .match(url.toString(), { ignoreSearch: true })
      .then((cached) => cached ?? fetch(request)),
  );
});
`;
}

export async function generateOfflineBuild({
  outputDirectory,
  basePath = process.env.COURSE_BASE_PATH ?? "/",
  courseReleaseDirectory,
}) {
  const normalizedBasePath = normalizeBasePath(basePath);
  if (courseReleaseDirectory !== undefined) {
    const releaseOutputDirectory = path.join(
      outputDirectory,
      COURSE_RELEASE_OUTPUT_PATH,
    );
    await rm(releaseOutputDirectory, { recursive: true, force: true });
    await mkdir(path.dirname(releaseOutputDirectory), { recursive: true });
    await cp(courseReleaseDirectory, releaseOutputDirectory, {
      recursive: true,
      filter: (sourcePath) => {
        const relativePath = path.relative(courseReleaseDirectory, sourcePath);
        return relativePath
          .split(path.sep)
          .every(
            (segment) =>
              segment === "" ||
              (!segment.startsWith(".") &&
                !PRIVATE_RELEASE_SEGMENTS.has(segment) &&
                !segment.endsWith(".pyc")),
          );
      },
    });
  }
  const assets = await collectBuildAssets(outputDirectory, normalizedBasePath);
  const manifest = createOfflineManifest(assets, normalizedBasePath);
  const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
  const serviceWorkerText = renderServiceWorker(manifest);

  await writeFile(
    path.join(outputDirectory, MANIFEST_FILENAME),
    manifestText,
    "utf8",
  );
  await writeFile(
    path.join(outputDirectory, SERVICE_WORKER_FILENAME),
    serviceWorkerText,
    "utf8",
  );

  return manifest;
}

const isMainModule =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;

if (isMainModule) {
  const projectRoot = path.dirname(
    path.dirname(fileURLToPath(import.meta.url)),
  );
  const manifest = await generateOfflineBuild({
    outputDirectory: path.join(projectRoot, "dist"),
    courseReleaseDirectory: path.join(projectRoot, "vendor", "current"),
  });
  process.stdout.write(
    `Offline shell ${manifest.version}: ${manifest.assets.length} files\n`,
  );
}
