# Values for Challenge 7: Wall-Range Pose Correction.

from math import pi

from ucsb_xrp import Pose, load_world


WORLD = load_world()
PHYSICAL_INITIAL_POSE = WORLD.initial_pose
ODOMETRY_INITIAL_POSE = Pose(
    PHYSICAL_INITIAL_POSE.x_mm + 80.0,
    PHYSICAL_INITIAL_POSE.y_mm - 60.0,
    PHYSICAL_INITIAL_POSE.heading_rad,
)
DESTINATION = WORLD.waypoint("destination")

X_WALL_MM = 900.0
Y_WALL_MM = 500.0
X_WALL_IS_POSITIVE = True
Y_WALL_IS_POSITIVE = True
SENSOR_FORWARD_OFFSET_MM = 70.0
X_SCAN_HEADING_RAD = 0.0
Y_SCAN_HEADING_RAD = pi / 2.0
WALL_OBSERVATION_HEADING_TOLERANCE_RAD = 0.10

RANGE_SAMPLE_COUNT = 7
MINIMUM_USABLE_RANGE_COUNT = 4
STOPPED_SPEED_MM_S = 5.0
